#
###################################
# Configuraçao base
####################################
#
title: nunogand
description: > # this means to ignore newlines until "baseurl:"
  Descrição para document head meta (Google search results) e feed.xml.
permalink: ':title/'
baseurl: "/teste_web" # the subpath of your site, e.g. /blog
url: "https://nunogand.com" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

#
###################################
# Autor
####################################
#
author: Nuno Rodrigues # add your name
author-img: logo_main.png # add your photo
about-author: Apontamentos e recortes dispersos; coisas portanto...
social-twitter: nunogand 
# social-facebook: # add your Facebook handle
social-github: nunogand # add your Github handle
#social-linkedin: # add your Linkedin handle
social-email: nunogand@gmail.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

#
###################################
# Jekyll config
####################################
#
# Build Settings
timezone: Europe/Lisbon
locale: pt-pt
markdown: kramdown
highlighter: rouge
future: true
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
enable_coderay: false

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
